[project]
name = "scoring-system"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ege-api",
    "ege-shared",
]

[tool.uv.sources]
ege-api = { workspace = true }
ege-shared = { workspace = true }

[tool.uv.workspace]
members = ["api_service", "shared"]
